### ISSUE TITLE
1.20 M1 Final Report Check & Submission

### ISSUE THREAD

**Issue by smmilk** [Kjkaikai/INF2001_P2-6#1]
**Task:** To complete each of the task under ToDo

**Goals:** Submit M1 Report

**Success criteria:** Clear indication of the processes, completion of each ToDo task

**Allocated time:** 3 Days

**Start date and end date:** 28/8 - 24/9

## ToDo

- [x] Introduction
- [x] Overall Description
- [x] Specific Requirements
- [x] Project Estimation and Plan
- [x] Use Case Description
- [x] Data Dictionary

**Comment by kaixinxxx** [comment]
Completed on 23/9/2023
