### ISSUE TITLE
1.18 Software Estimation & Budget

### ISSUE THREAD

**Issue by Kjkaikai** [Kjkaikai/INF2001_P2-6#18]
Task: To calculate the software estimation and budget of project

Goals: Find the overall project budget which consist of finding estimation of effort and size

Success criteria: Clear indication of the processes, a number figure and calculation to support the final budget

Allocated time: 2 Days

Start date and end date: 15/09 - 16/9

**Comment by marcusye0** [comment]
completed on 22/9/23
