### ISSUE TITLE
1.12 Use Case Diagram

### ISSUE THREAD

**Issue by smmilk** [Kjkaikai/INF2001_P2-6#2]
**Task:** To design the use case diagram

**Goals:** To visualize the different types of roles in a system and how those roles interact with the system

**Success criteria:** Demonstrated the different ways that a user might interact with a system

**Allocated time:** 5 Days

**Start date and end date:** 3/9 - 7/9

**Comment by kaixinxxx** [comment]
Done on 22/9/23
