### ISSUE TITLE
1.8 Non-Functional Requirements

### ISSUE THREAD

**Issue by marcusye0** [Kjkaikai/INF2001_P2-6#20]
**Task:** To write up non-functional requirements of the project.

**Goals:** Specify the timing relationships for real time systems. Make such requirements as specific as possible. Define any user identity authentication requirements.

**Success criteria:** Clear and concise requirements

**Allocated time:** 3 Days

**Start date and end date:** 31/8 - 2/9

**Comment by kaixinxxx** [comment]
Done on 29/9/2023
