### ISSUE TITLE
1.7 Functional Requirements

### ISSUE THREAD

**Issue by marcusye0** [Kjkaikai/INF2001_P2-6#21]
**Task:** To write up functional requirements of the project Functional requirements capture the intended behavior of the system. This behavior may be
expressed as services, tasks or functions the system is required to perform

**Goals:** List in detail the different product functions.

**Success criteria:** Clear and concise requirements that align with intended behavior of the system

**Allocated time:** 7 Days

**Start date and end date:** 31/8 - 6/9

**Comment by smmilk** [comment]
Done and vetted
