### ISSUE TITLE
1.17 Calculate Estimation Of Effort

### ISSUE THREAD

**Issue by smmilk** [Kjkaikai/INF2001_P2-6#30]
**Task:** To estimate the manpower and time required

**Goals:** Aid in designing of chart and project management

**Success criteria:** Consider all aspects of project in calculation

**Allocated time:** 2 Days

**Start date and end date:** 15/9 - 16/9

**Comment by Kjkaikai** [comment]
Found minor calculation error and amended it in the m1 report

**Comment by Kjkaikai** [comment]
100% complete
