### ISSUE TITLE
1.1 Intended Audience and Document Overview

### ISSUE THREAD

**Issue by smmilk** [Kjkaikai/INF2001_P2-6#33]
**Task:** To describe the intended audience for M1 report, and what the rest of the report contains.

**Goals:** Suggest a sequence for reading the document, beginning with the overview sections and proceeding through the sections that are most pertinent to each reader type.

**Success criteria:** Described in detail all the different types of reader that the document is intended for and how the report is organised

**Allocated time:** 4 Days

**Start date and end date:** 28/8 - 31/8

**Comment by kaixinxxx** [comment]
Done on 29/9/2023
