### ISSUE TITLE
1.9 User Interface Requirements

### ISSUE THREAD

**Issue by smmilk** [Kjkaikai/INF2001_P2-6#37]
**Task:** To describe the logical characteristics of each interface between the software product and the users

**Goals:** Use the graphic from the project description as the basis for user interface

**Success criteria:** Shown graphic for the thermostat user interface and provided basic description as to how users will interact

**Allocated time:** 4 Days

**Start date and end date:** 3/9 - 6/9

**Comment by KevinTanTF** [comment]
Reviewed Completed
