### ISSUE TITLE
1.10 Performance Requirement

### ISSUE THREAD

**Issue by smmilk** [Kjkaikai/INF2001_P2-6#38]
**Task:** To do up performance requirements for the product under various circumstances, state them and explain their rationale

**Goals:** Help the developers understand the intent and make suitable
design choices

**Success criteria:** Specify the timing relationships for real time systems. Make such requirements as specific as possible

**Allocated time:** 4 Days

**Start date and end date:** 3/9 - 6/9

**Comment by marcusye0** [comment]
completed on 22/9/23
