### ISSUE TITLE
2.2 Design Component Diagram

### ISSUE THREAD

**Issue by smmilk** [Kjkaikai/INF2001_P2-6#41]

**Comment by Kjkaikai** [comment]
A component diagram in Unified Modeling Language (UML) is a type of structural diagram that provides a visual representation of the high-level components within a system and their interrelationships. It is particularly useful for illustrating the organization and dependencies among components in a software or system architecture. The component diagram will be cross-referenced with our Use Case Diagram, Use Case Description, and Class Diagram.

**Comment by Kjkaikai** [comment]
started drafting component diagram on 15/10/23

**Comment by Kjkaikai** [comment]
![Image](https://github.com/Kjkaikai/INF2001_P2-6/assets/58503698/f305cbdc-4efd-4549-9289-63bcd5e71180)


This was the draft component diagram. Feedback from the professor was that he felt that database should not directly communicate with the landing page. The professor recommended to follow the MVC model as he feel that there may be a problem if security concerns were to be asked as there may be a threat of hacking into the system with the current design. Prof also mentioned that I may design it to show in a 3-tier way like client side, presentation, logic side

- Will improve on it and update again

**Comment by Kjkaikai** [comment]
![Image](https://github.com/Kjkaikai/INF2001_P2-6/assets/58503698/4a47264b-302e-4873-b221-ea39e641605a)


Updated Component diagram as of 25 Oct 2023

**Comment by marcusye0** [comment]
Completed Component Diagram as of 27 Oct 2023

![Image](https://github.com/Kjkaikai/INF2001_P2-6/assets/113745349/3d213496-e8e4-4443-a75f-6229c5c68c51)
