### ISSUE TITLE
2.3 Design Class Diagram

### ISSUE THREAD

**Issue by smmilk** [Kjkaikai/INF2001_P2-6#42]

**Comment by Kjkaikai** [comment]
EmployeeConnect Domain model describes main classes and relationships which could be used during analysis phase to better understand domain area for shift management system (SMS).

**Comment by Kjkaikai** [comment]
started listing down all of the classes in the class diagram on 2/10/23

**Comment by Kjkaikai** [comment]
A class diagram in Unified Modeling Language (UML) is a type of structural diagram that provides a visual representation of the static structure of a system by illustrating classes, their attributes, methods, relationships, and the constraints governing them. Class diagrams are fundamental to object-oriented modeling and design.

**Comment by Kjkaikai** [comment]
These are the different types of relationship and notation in a class diagram

source: https://medium.com/@uferesamuel/uml-class-diagrams-the-simple-approach-eee2d1ffc125


![Image](https://github.com/Kjkaikai/INF2001_P2-6/assets/58503698/9f2283f6-17ed-4314-84b5-84e396fbb831)

**Comment by marcusye0** [comment]
Completed as of 27 October 2023

![Image](https://github.com/Kjkaikai/INF2001_P2-6/assets/113745349/75ba7d78-aa1e-4803-ac26-1217780a6586)
