### ISSUE TITLE
2.4 Design Sequence Diagram

### ISSUE THREAD

**Issue by smmilk** [Kjkaikai/INF2001_P2-6#43]

**Comment by Kjkaikai** [comment]
A sequence diagram is a type of interaction diagram in Unified Modeling Language (UML) that illustrates how different components or objects in a system interact with each other in a specific scenario or over a period of time. It focuses on the sequence of messages exchanged between objects to achieve a particular behavior. Sequence diagrams are particularly useful for visualizing the dynamic aspects of a system, especially in terms of the order of interactions.

Our assignment involves designing the two most comprehensive and central use cases for our proposed system. These will be cross-referenced with our Use Case Diagram, Use Case Description, and Class Diagram.

**Comment by Kjkaikai** [comment]
Here are key components and concepts associated with a sequence diagram:

**Objects/Participants:**
Lifelines: Represent individual objects or actors in the system. They are depicted as vertical lines, and each line represents the lifespan of an object during the scenario.

**Messages:**
Arrowed Lines: Represent the flow of messages between lifelines. They indicate the order and direction of communication between objects.
Activation Bar: A vertical dashed line along the lifeline indicating the period when an object is active and processing a message.

**Activation and Deactivation:**
Activation: Represents the period during which an object is actively processing a message. It is depicted by extending a dashed line downwards from the lifeline.
Deactivation: Represents the end of the period during which an object is actively processing a message. It is depicted by a dashed line moving upwards from the lifeline.

**Focus of Control:**
Focus of Control: Shows the focus of control or the flow of execution among different objects in the system.

**Combined Fragments:**
Alt (Alternative): Represents alternative paths or scenarios in a sequence diagram.
Opt (Optional): Represents optional elements or messages.
Loop: Represents a loop or iteration in the sequence of messages.
Par (Parallel): Represents parallel or concurrent behavior.


**Interaction Occurrences:**
Found Messages: Messages that are found within the interaction, but their specific order is not determined.

**Comment by marcusye0** [comment]
Consulted Professor Quah on the sequence diagram, ,the following items will to be changed: 

-adjust the arrows of the diagram so that it flows downwards from left to right
- entity class have to be added for both the sequence diagram
- alternative scenarios should all be included in the diagram

**Comment by marcusye0** [comment]
updated and change the 2 sequence diagram after consultation

**Comment by marcusye0** [comment]
completed 2 sequence diagram as of 27 October 2023

**Comment by marcusye0** [comment]
![Image](https://github.com/Kjkaikai/INF2001_P2-6/assets/113745349/3d771f0e-4ca7-4f0f-bc4f-976273a7dbe3)
![Image](https://github.com/Kjkaikai/INF2001_P2-6/assets/113745349/2292b9fa-bfcb-4364-8d05-ad90afa7e244)
