### ISSUE TITLE
3.1 Setup Database

### ISSUE THREAD

**Issue by marcusye0** [Kjkaikai/INF2001_P2-6#48]
Task: To create and setup database

Goals: Making sure tables are created

Success criteria: No issues connecting

Allocated time: 3 Days

Start date and end date: 30/10 - 1/11

**Comment by smmilk** [comment]
![Image](https://github.com/Kjkaikai/INF2001_P2-6/assets/114944576/68243da2-9618-464e-881f-f727e862edb1)

Created database on local machine
