### ISSUE TITLE
3.2 User Manual Documentation of Prototype

### ISSUE THREAD

**Issue by marcusye0** [Kjkaikai/INF2001_P2-6#49]
Task: Documenting the user manual for the prototype.

Goals: Provide clear and comprehensive instructions for users.
Highlight key features and functionalities of the prototype.
Address common user issues and troubleshooting steps.

Success criteria: User manual is easily understandable by the target audience.
Users can follow the instructions to perform key tasks without confusion.
Vetted regarding the clarity and usefulness of the documentation.

Allocated time: 13 Days

Start date and end date: 30/10 - 11/11

**Comment by smmilk** [comment]
![Image](https://github.com/Kjkaikai/INF2001_P2-6/assets/114944576/b6bde503-396b-4016-a3da-03f7626ea35e)


Insert figma screenshots

**Comment by smmilk** [comment]
![Image](https://github.com/Kjkaikai/INF2001_P2-6/assets/114944576/d0de1292-924c-4ef4-8d50-309d110f5034)

Detailed explainations per usecase
