### ISSUE TITLE
3.3 Developing Manager Pages

### ISSUE THREAD

**Issue by marcusye0** [Kjkaikai/INF2001_P2-6#50]
Task: Create prototype for Manager function

Goals: Making sure linking is correct in figma

Success criteria: Demonstrates functions accurately 

Allocated time: 13 Days

Start date and end date: 30/10 - 11/11

**Comment by smmilk** [comment]
![Image](https://github.com/Kjkaikai/INF2001_P2-6/assets/114944576/53d6b28a-947f-4159-bdd0-9f80c7b127a3)

Manager pages done and vetted
