### ISSUE TITLE
3.3.1 Developing Employee Pages

### ISSUE THREAD

**Issue by marcusye0** [Kjkaikai/INF2001_P2-6#51]

**Comment by KevinTanTF** [comment]
Task: Create prototype for Employee function

Goals: Making sure linking is correct in figma

Success criteria: Demonstrates functions accurately

Allocated time: 13 Days

Start date and end date: 30/10 - 11/11

**Comment by KevinTanTF** [comment]
![Image](https://github.com/Kjkaikai/INF2001_P2-6/assets/122594693/97ca0d50-dbdf-4b21-8216-26b73d3ea604)


100% Done and Completed
