### ISSUE TITLE
3.3.3 Developing Manager Ferry Management Page

### ISSUE THREAD

**Issue by marcusye0** [Kjkaikai/INF2001_P2-6#53]
Task: Create prototype for Ferry management function

Goals: Making sure linking is correct in figma

Success criteria: Demonstrates functions accurately

Allocated time: 13 Days

Start date and end date: 30/10 - 11/11

**Comment by kaixinxxx** [comment]
Completed on 25/11/23

![Image](https://github.com/Kjkaikai/INF2001_P2-6/assets/113665616/fb814ca6-7a3f-4423-bee6-5f0f5644a111)
