### ISSUE TITLE
4.5 Project Prototype & Wireframes

### ISSUE THREAD

**Issue by Kjkaikai** [Kjkaikai/INF2001_P2-6#61]
Task: Check through prototype and screenshot the necessary wireframes

Goals: Ensure all wireframes needed are screenshotted and placed in correct sequence 

Success criteria: Able to illustrate and demonstrates the flow of the use case correctly

Allocated time: 5 Days

Start date and end date: 17/11 - 21/11

**Comment by KevinTanTF** [comment]
![Image](https://github.com/Kjkaikai/INF2001_P2-6/assets/122594693/f2e13310-4483-4d58-94eb-e0196f6f3a9d)

100% Done and Completed
